### ISSUE TITLE
Boss kill trigger for Aga1 and Aga2

### ISSUE THREAD

**Issue by MichaelWolverineStream** [freddyJarva/lttp-autotimer#23]
0x3C5 == 0x03 when Aga1 is dead

Aga2 I don't know what to look for

**Comment by freddyJarva** [comment]
Perhaps the sprite of aga lying down can be checked for?

**Comment by MichaelWolverineStream** [comment]
I assumed this was tested but maybe not.
High byte 8 in the Room Data adress informs about "boss battle won".

**Comment by freddyJarva** [comment]
Ah yes, I tested it for crystal/pendant dungeons. Decided to not use it for those because it was tedious finding the room tiles, and it didn't trigger until 10 seconds after picking up the crystal/pendant.

But it should work nicely for these two!
