### ISSUE TITLE
Opening of doors or bonkable/bombable walls

### ISSUE THREAD

**Issue by MichaelWolverineStream** [freddyJarva/lttp-autotimer#25]
In Room Data, 0x000* to 0x24F*, the High Byte 128, 64, 32, and 16 are used to track if doors are unlocked/bombed or other means.

The problem is probably when you want to track bombable wall entrances from the OW, where I believe you have to check the corresponding bit in the specific room in the UW...

**Comment by freddyJarva** [comment]
Do you have a good reference as to which room corresponds to which address? It becomes 99% less of a pain to map this up with that information!

**Comment by MichaelWolverineStream** [comment]
For the OW:
the 4 bytes at 7E0487-7E0489 is the tilemap for all bombable walls in the OW. It is ugly but simplest to track, because the alternative is to use event information byte for each OW tile at 0x280* to 0x2FF* which I don't think is necessary. I don't think there's ever more than 1 bombable wall in each supertile in the OW either.

For the UW:
the room data addresses are not updated until you transition, so we have to read a different value.
7E0401 describes which keydoors/bombable walls/bonkable walls have been opened in the current room.
We could identify all rooms with bombable walls and the exact sram mask needed for each different bombable wall in those rooms. It wouldn't be hard, since it's not that many, so we just need a framework in the json for this.

**Comment by freddyJarva** [comment]
closed by #51
