### ISSUE TITLE
Add compasses and maps to items 

### ISSUE THREAD

**Issue by freddyJarva** [freddyJarva/lttp-autotimer#5]
Compasses and maps are not logged at the moment. Address `0x428`, taken from [here](http://alttp.mymm1.com/wiki/ALTTPR_SRAM_Map#Rando_Specific_Assignments_.26_Game_Stats:_0x3F1.2A_to_0x4FD.2A), together with a current tile check will suffice for normal game modes.

> Maps & Compasses: 0x428*
>
> m m m m c c c c
>
> Number of maps and compasses collected represented as four bit integers.
> m - Maps
> c - Compasses

**Comment by MichaelWolverineStream** [comment]
specific dungeon maps and compasses will be found at 0x364-0x369:
http://alttp.mymm1.com/wiki/ALTTPR_SRAM_Map#Items_.26_Equipment:_0x340.2A_to_0x3F0.2A
